# Renders a month's README.md: a one-page summary of its season.jsonc that GitHub shows when you open the
# month's folder. The full detail (every role, the light-mode changes) stays in theme-definition.md.
# Called by Generate-Themes.ps1 once per month, with the month's base-mode season.
param($Season, [hashtable]$Files)

Set-StrictMode -Version Latest

$data = $Season.Data
$lines = [System.Collections.Generic.List[string]]::new()
function Add([string]$Line = '') { $lines.Add($Line) }
function Cell([string]$Text) { ($Text ?? '') -replace '\|', '\|' -replace "`r?`n", ' ' }
function Title([string]$Text) { (Get-Culture).TextInfo.ToTitleCase($Text) }

function Format-Date([string]$MonthDay) {
    [datetime]::ParseExact("2000-$MonthDay", 'yyyy-MM-dd', [cultureinfo]::InvariantCulture).ToString('MMM d', [cultureinfo]::InvariantCulture)
}

# "Pumpkin orange `#D35400`" for a colour role, using the palette's display name.
function Describe-Color([string]$Role) {
    $color = $Season.Colors[$Role]
    $name = $Season.Palette.Contains($color.Ref) ? $Season.Palette[$color.Ref].Name : $color.Ref
    "$name ``$($color.Hex.ToUpper())``"
}

function Icon([string]$Role) { $Season.Icons[$Role].Value }

$modeSeasons = $Season['ModeSeasons'] ?? @{ $Season.Mode = $Season }
$otherModes = @($modeSeasons.Keys | Where-Object { $_ -ne $Season.Mode } | Sort-Object)
$modes = @($Season.Mode) + $otherModes
$variants = @($Season.Variants)

Add '<!-- Generated by Generate-Themes.ps1 from season.jsonc. Edit season.jsonc, not this file. -->'
Add
Add "# $(Icon 'shell') $($Season.Month): $($data.name)"
Add
Add "> $($data.tagline)"
Add
foreach ($paragraph in @($data['description'] ?? @())) { Add $paragraph; Add }

# Both VS Code previews side by side, dark first.
$previews = foreach ($mode in $modes) {
    $key = $mode -eq $Season.Mode ? 'vscode-preview' : "vscode-preview@$mode"
    if ($Files[$key]) { "<img src=`"$($Files[$key])`" width=`"49%`" alt=`"$($Season.Month) in VS Code, $mode`">" }
}
if ($previews) {
    Add "<p>$($previews -join ' ')</p>"
    Add
}

if ($data['holidays']) {
    $holidays = foreach ($h in $data.holidays) { "$($h.name) ($(Format-Date $h.date)$($h['note'] ? ", $($h.note)" : ''))" }
    Add "- **Holidays:** $($holidays -join '; ')"
}
if ($data['mood']) { Add "- **Mood:** $($data.mood -join ', ')" }
Add "- **Modes:** $(($modes | ForEach-Object { $_ -eq $Season.Mode ? "$_ (default)" : $_ }) -join ', ')"
if ($variants.Count) {
    Add "- **Variants:** $(($variants | ForEach-Object { "$($_.name) ($(Format-Date $_.from) to $(Format-Date $_.to))" }) -join '; ')"
}
Add

Add '## Colours'
Add
Add '| Role | Colour |'
Add '|---|---|'
$seen = @{}
foreach ($role in 'brand.primary', 'brand.secondary', 'brand.tertiary', 'brand.accent', 'brand.highlight') {
    $hex = $Season.Colors[$role].Hex.ToUpper()
    if ($seen.ContainsKey($hex)) { continue }
    $seen[$hex] = $true
    Add "| $(Title ($role -replace '^brand\.', '')) | $(Describe-Color $role) |"
}
$vscode = $data['targets'] ? $data.targets['vscode'] : $null
$statusRole = ($vscode ? $vscode['status_bar'] : $null) ?? 'brand.primary'
Add "| VS Code status bar | $(Describe-Color $statusRole) |"
foreach ($mode in $modes) {
    $page = $modeSeasons[$mode]
    $name = $page.Palette.Contains($page.Colors['ui.background'].Ref) ? $page.Palette[$page.Colors['ui.background'].Ref].Name : ''
    if ($name -like 'Light-mode *') { $name = '' }   # New-LightMode's generic names add nothing here
    Add "| $(Title $mode) editor background | $("$name ".TrimStart())``$($page.Colors['ui.background'].Hex.ToUpper())`` |"
}
Add
if ($Files['palette-svg']) { Add "![$($Season.Month) palette]($($Files['palette-svg']))"; Add }

Add '## Icons'
Add
$iconRoles = [ordered]@{ Shell = 'shell'; Admin = 'root'; Folder = 'path'; Home = 'home'; Git = 'git'; 'Run time' = 'exec_time'; Clock = 'clock'; Success = 'status_ok'; Failure = 'status_err' }
Add "| $($iconRoles.Keys -join ' | ') |"
Add "|$(($iconRoles.Keys | ForEach-Object { '---' }) -join '|')|"
Add "| $(($iconRoles.Values | ForEach-Object { Icon $_ }) -join ' | ') |"
Add
Add 'The prompt, illustrated:'
Add
Add '```text'
Add "╭─$(Icon 'shell') pwsh  $(Icon 'path') ~/code  $(Icon 'git') main ✏️ ~1  $(Icon 'exec_time') 12ms          $(Icon 'clock') 7:30 PM"
Add "$(Icon 'prompt')──$(Icon 'status_ok')"
Add '```'
Add

Add '## Use it'
Add
$themes = foreach ($mode in $modes) { "*$($modeSeasons[$mode].Title)*" }
Add "- **VS Code:** pick $($themes -join ' or ') with **Preferences: Color Theme**. The Seasonal Themes extension switches to it during $($Season.Month) on its own."
$prompts = foreach ($mode in $modes) {
    $key = $mode -eq $Season.Mode ? 'oh-my-posh' : "oh-my-posh@$mode"
    if ($Files[$key]) { "[$($Files[$key])]($($Files[$key])) ($mode)" }
}
Add "- **Oh My Posh:** $($prompts -join ', '). ``Get-SeasonalTheme.ps1`` picks the right one for today."
Add

foreach ($variant in $variants) {
    Add "## $($variant.name)"
    Add
    Add "$(Format-Date $variant.from) to $(Format-Date $variant.to)$($variant['tagline'] ? ": $($variant.tagline)" : '')."
    Add
    $vp = foreach ($mode in $modes) {
        $key = "vscode-preview:$($variant.id)" + ($mode -eq $Season.Mode ? '' : "@$mode")
        if ($Files[$key]) { "<img src=`"$($Files[$key])`" width=`"49%`" alt=`"$($variant.name) in VS Code, $mode`">" }
    }
    if ($vp) { Add "<p>$($vp -join ' ')</p>"; Add }
    $vfiles = foreach ($mode in $modes) {
        $key = "oh-my-posh:$($variant.id)" + ($mode -eq $Season.Mode ? '' : "@$mode")
        if ($Files[$key]) { "[$($Files[$key])]($($Files[$key])) ($mode)" }
    }
    if ($vfiles) { Add "Oh My Posh: $($vfiles -join ', ')."; Add }
}

Add '---'
Add
$details = $Files['theme-definition'] ? "[$($Files['theme-definition'])]($($Files['theme-definition']))" : 'theme-definition.md'
Add "Every colour role, the light-mode changes and all generated files are in $details. To change the month, edit [season.jsonc](season.jsonc) and run ``pwsh ./Generate-Themes.ps1``."

($lines -join "`n") + "`n"
