# Renders a month's human-readable theme page from its resolved season. Called by Generate-Themes.ps1.
param($Season, [hashtable]$Files)

Set-StrictMode -Version Latest

$data = $Season.Data
$lines = [System.Collections.Generic.List[string]]::new()
function Add([string]$Line = '') { $lines.Add($Line) }

function Format-Cell([string]$Text) { ($Text ?? '') -replace '\|', '\|' -replace "`r?`n", ' ' }

function Format-Date([string]$MonthDay) {
    [datetime]::ParseExact("2000-$MonthDay", 'yyyy-MM-dd', [cultureinfo]::InvariantCulture).ToString('MMM d', [cultureinfo]::InvariantCulture)
}

function Format-CodePoints([string]$Text) {
    (@($Text.EnumerateRunes()) | ForEach-Object { 'U+{0:X4}' -f $_.Value }) -join ' '
}

function Get-Paragraphs($Prose) {
    if ($null -eq $Prose) { @() } elseif ($Prose -is [string]) { @($Prose) } else { @($Prose) }
}

# Summarises what a variant changes, e.g. "palette (2), colors.brand (3), icons (4)".
function Get-VariantChanges($Variant) {
    $parts = foreach ($key in $Variant.Keys) {
        if ($key -in 'id', 'name', 'from', 'to') { continue }
        $value = $Variant[$key]
        if ($key -eq 'colors' -and $value -is [System.Collections.IDictionary]) {
            foreach ($group in $value.Keys) { "colors.$group ($($value[$group].Count))" }
        }
        elseif ($value -is [System.Collections.IDictionary]) { "$key ($($value.Count))" }
        else { $key }
    }
    $parts -join ', '
}

Add '<!-- Generated by Generate-Themes.ps1 from season.jsonc. Edit season.jsonc, not this file. -->'
Add
Add "# $($Season.Month): $($data.name)"
Add
Add "> $($data.tagline)"
Add
if ($Files['palette-svg']) {
    Add "![$($Season.Month) palette]($($Files['palette-svg']))"
    Add
}
foreach ($paragraph in Get-Paragraphs $data['description']) {
    Add $paragraph
    Add
}

Add '| | |'
Add '|---|---|'
Add "| **Appearance** | $($data.appearance) |"
if ($data['mood']) { Add "| **Mood** | $(Format-Cell ($data.mood -join ', ')) |" }
if ($data['holidays']) {
    $holidays = $data.holidays | ForEach-Object {
        $text = "$($_.name) ($(Format-Date $_.date))"
        if ($_['note']) { $text += ", $($_.note)" }
        $text
    }
    Add "| **Holidays** | $(Format-Cell ($holidays -join '; ')) |"
}
if ($data['keywords']) { Add "| **Imagery** | $(Format-Cell ($data.keywords -join ', ')) |" }
Add

Add '## Palette'
Add
Add '| Key | Name | Hex | Note |'
Add '|---|---|---|---|'
foreach ($entry in $Season.Palette.GetEnumerator()) {
    Add "| ``$($entry.Key)`` | $(Format-Cell $entry.Value.Name) | ``$($entry.Value.Hex.ToUpper())`` | $(Format-Cell $entry.Value.Note) |"
}
Add

Add '## Colour roles'
Add
Add 'Roles marked *inherits* are not set in `season.jsonc` and take the colour of the role named.'
Add
foreach ($group in $Season.Roles.Groups.Keys) {
    $title = $group -eq 'ui' ? 'UI' : (Get-Culture).TextInfo.ToTitleCase($group)
    Add "### $title"
    Add
    if ($Season.Roles.Groups[$group]) { Add $Season.Roles.Groups[$group]; Add }
    $showContrast = $group -eq 'brand'
    if ($showContrast) {
        Add '| Role | Colour | Hex | Text on it | Notes |'
        Add '|---|---|---|---|---|'
    }
    else {
        Add '| Role | Colour | Hex | Notes |'
        Add '|---|---|---|---|'
    }
    foreach ($key in $Season.Roles.Colors.Keys) {
        $role = $Season.Roles.Colors[$key]
        if ($role.Group -ne $group) { continue }
        $color = $Season.Colors[$key]
        $notes = @()
        if ($color.From) { $notes += "*inherits* ``$($color.From)``" }
        if ($color.Style) { $notes += $color.Style }
        $ref = $color.Ref -match '^#' ? '' : $color.Ref
        $cells = "| ``$($role.Role)`` | $ref | ``$($color.Hex.ToUpper())`` |"
        if ($showContrast) { $cells += (' `{0}` {1:N1}:1 |' -f $color.On.ToUpper(), $color.Contrast) }
        Add "$cells $($notes -join ', ') |"
    }
    Add
}

Add '## Icons'
Add
Add '| Role | Icon | Code points | Notes |'
Add '|---|---|---|---|'
foreach ($role in $Season.Roles.Icons.Keys) {
    $icon = $Season.Icons[$role]
    $note = switch ($icon.From) {
        $null { '' }
        'default' { '*default*' }
        default { "*inherits* ``$_``" }
    }
    Add "| ``$role`` | $($icon.Value) | $(Format-CodePoints $icon.Value) | $note |"
}
Add

if ($Season.Lang.Count) {
    Add "**Languages and tools** (anything not listed uses ``language``: $($Season.Icons['language'].Value))"
    Add
    Add '| Segment | Icon |'
    Add '|---|---|'
    foreach ($entry in $Season.Lang.GetEnumerator()) { Add "| ``$($entry.Key)`` | $($entry.Value) |" }
    Add
}
if ($Season.Os.Count) {
    Add "**Operating systems** (anything not listed uses ``shell``: $($Season.Icons['shell'].Value))"
    Add
    Add '| OS | Icon |'
    Add '|---|---|'
    foreach ($entry in $Season.Os.GetEnumerator()) { Add "| ``$($entry.Key)`` | $($entry.Value) |" }
    Add
}
if ($Season.Pool.Count) {
    Add "**Spares:** $($Season.Pool -join ' ')"
    Add
}

if ($Season.Variants.Count) {
    Add '## Variants'
    Add
    Add '| Variant | Dates | Changes | Files |'
    Add '|---|---|---|---|'
    foreach ($variant in $Season.Variants) {
        $variantFiles = $Files.Keys | Where-Object { $_ -like "*:$($variant.id)" } | Sort-Object |
            ForEach-Object { "[$($Files[$_])]($($Files[$_]))" }
        Add "| $(Format-Cell $variant.name) | $(Format-Date $variant.from) to $(Format-Date $variant.to) | $(Get-VariantChanges $variant) | $($variantFiles -join ', ') |"
    }
    Add
}

if ($Files['vscode-theme']) {
    Add '## VS Code'
    Add
    Add "Theme: [$($Season.Title)]($($Files['vscode-theme'])), part of the Seasonal Themes extension in ``vscode/``."
    Add
    if ($Files['vscode-preview']) {
        Add "![$($Season.Month) in VS Code]($($Files['vscode-preview']))"
        Add
    }
}

if ($data['ideas']) {
    Add '## Ideas'
    Add
    foreach ($idea in $data.ideas) { Add "- $idea" }
    Add
}

if ($data['links']) {
    Add '## Links'
    Add
    foreach ($link in $data.links) { Add "- [$($link.title)]($($link.url))" }
    Add
}

Add '## Generated files'
Add
if ($Files['oh-my-posh']) {
    Add "- [$($Files['oh-my-posh'])]($($Files['oh-my-posh'])): Oh My Posh prompt."
    Add "  Try it with ``oh-my-posh init pwsh --config <repo>/$($Season.Month)/$($Files['oh-my-posh']) | Invoke-Expression``."
}
if ($Files['palette-svg']) { Add "- [$($Files['palette-svg'])]($($Files['palette-svg'])): palette swatch sheet." }
if ($Files['vscode-theme']) { Add "- [$($Files['vscode-theme'])]($($Files['vscode-theme'])): VS Code colour theme." }
if ($Files['vscode-preview']) { Add "- [$($Files['vscode-preview'])]($($Files['vscode-preview'])): preview of the VS Code theme." }

($lines -join "`n") + "`n"
